### ISSUE TITLE
v1 Wallets

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#154]
- [x] Have all addresses be attached to a wallet ID. Wallets can be keyed on [wallet ID] + [user ID], so everyone will have a wallet with ID 0 to start.
- [x] When adding a new paybutton, allow them to select the desired wallet to attach it to in a dropdown. If they only have 1 wallet, grey out the dropdown so it just shows as being attached to the default wallet.
- [x] List all wallets on the Wallets page.
- [x] Allow creation of a new wallet, where all they do is choose the name and network.
- [x] Wallets will have an (wallet) ID, user ID, name, network, createdAt, updatedAt (new DB table).
- [x] When a user account is created, they're assigned a wallet call "Default Wallet" with an ID (index) of 0.
- [ ] Allow existing wallets to have their names changed.

**Comment by chedieck** [comment]
Should `Address` <-> `Wallet` be one-to-many? As in: it is possible for different users have different wallets pointing to the same address; but each wallet will only point to one address.

**Comment by Klakurka** [comment]
- many to many for the addresses <-> wallets feels right to me -- give people more freedom to do what they want.
- also, allowing them to have more than 1 currency in a wallet also seems totally fine to me. So for example for our company, we'd have a "Coin Dance" wallet which has both XEC and BCH (addresses) in it.
