### ISSUE TITLE
Implement automatic transactions sync

### ISSUE THREAD

**Issue by chedieck** [PayButton/paybutton-server#177]
For the sync process, I'd like for us to have 2 components there.

Piece one is what you made, the api we can call to sync up while the user has been offline. This would run at login time.

Piece two would be a socket connection that subscribes to all of the relevant addresses that would execute an update (possibly just running the sync command again) in realtime.

_Originally posted by @Klakurka in https://github.com/PayButton/paybutton-server/issues/176#issuecomment-1189302492_

**Comment by Klakurka** [comment]
Related to https://github.com/PayButton/paybutton-server/issues/88.
