### ISSUE TITLE
Have dev sites include a button that uses the custom URL of the API

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#18]
When we create a dev instance through Netlify, the buttons on the page should have their API endpoints set to that URL instead of api.paybutton.org.

**Comment by Klakurka** [comment]
Basically this: https://github.com/PayButton/paybutton/issues/58

**Comment by alcipir** [comment]
good idea, adding on my pipeline :)

**Comment by Klakurka** [comment]
We pretty much did the main component of this on the client already. In the config, the URL can be set to anything.
