### ISSUE TITLE
Remove non v1 nav items 

### ISSUE THREAD

**Issue by johnkuney** [PayButton/paybutton-server#187]
Account, Settings, and Help can remove for now

Wallets can just statically show 1 'Default Wallet`

Networks we can probably just complete what's in the v1 task

**Comment by Klakurka** [comment]
I'm fine with us going ahead with the Account v1 task (#156) if it's easy but I'll leave that up to the guys to decide.

**Comment by johnkuney** [comment]
added in pr #190
