### ISSUE TITLE
Transaction hash shouldn't be unique alone

### ISSUE THREAD

**Issue by chedieck** [PayButton/paybutton-server#219]
Better explained with an example:

**Problem:**

Let [qrmm7edwuj4jf7tnvygjyztyy0a0qxvl7quss2vxek](https://ecashexplorer.com/address/ecash:qrmm7edwuj4jf7tnvygjyztyy0a0qxvl7quss2vxek)  be **address A** and [qzchtgjam2fs68tunggjgvf9h7v9yuv0dqal9p5pcs](https://ecashexplorer.com/address/ecash:qzchtgjam2fs68tunggjgvf9h7v9yuv0dqal9p5pcs) be **address B**.

Notice the transaction below:
![image](https://user-images.githubusercontent.com/21281174/186683440-0b83b50c-66d0-4fd7-b2b9-dcd79ed184ad.png)

It sends outputs both to address A and address B: 24.68 and 33186.04, respectively. When saving this in the database, the address listed lastly will have the transaction saved (with the amount relevant to it) by overwriting the previously saved transaction (with the amount that was relevant to it), because the hash is being checked for uniqueness.

**Solution:**

Instead of having the `hash` as unique, have the `hash` be unique together with the `addressId` to which the transaction points.
That way, we could have:
```
+----+------------------------------------------------------------------+----------------+------------+-----------+
| id | hash                                                             | amount         | timestamp  | addressId |
+----+------------------------------------------------------------------+----------------+------------+-----------+
| 23 | 0d5a7564e2a9772620603c1b185343a3772577b66c037f388df42427c516af93 |    24.68000000 | 1616902919 |         1 |
|  1 | 0d5a7564e2a9772620603c1b185343a3772577b66c037f388df42427c516af93 | 33186.04000000 | 1616902919 |         3 |
+----+------------------------------------------------------------------+----------------+------------+-----------+
```

**Comment by Klakurka** [comment]
We can do this but then we'll have a situation where it'll say there were 2 payments instead of 1 if both addresses are attached to a button.

If somebody makes a tx with 10 outputs all going to the same address, we should make sure those values are summed up rather than showing as 10 separate txs.

I think BIP 70 won't have this problem.

**Comment by chedieck** [comment]
> We can do this but then we'll have a situation where it'll say there were 2 payments instead of 1 if both addresses are attached to a button.

Indeed, if I create a button with the two addresses from the example above, the same transaction will be listed twice:
![image](https://user-images.githubusercontent.com/21281174/186902206-9aec99bf-adfa-43fb-bb50-0c78502c3de6.png)
But isn't that the case? It's the same transaction, but with two outputs to different addresses.

The `Transaction` object has a foreign key to some address. Therefore, the transactions inputs & outputs that are considered for calculating the `amount` column for the `Transaction` object are only those that have this address as source or destination, respectively. In the example above, one of the addresses received 24.68 XEC as payment, while the other received 33186.04 XEC.

> If somebody makes a tx with 10 outputs all going to the same address, we should make sure those values are summed up rather than showing as 10 separate txs.


This is the case already. This PR only changes so that different outputs to different addresses are saved differently.
