### ISSUE TITLE
Handle mempool txs as well (not just ones that have been confirmed)

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#349]
- Show if finalized (XEC only)
- Remove if they become invalid later

No need to tell people if they've been confirmed or not -- just drop them if they become invalid later.

**Comment by chedieck** [comment]
- [ ] Subscribe addresses to data stream of mempool txs (#350)
- [ ] Also fetch unconfirmed txs when syncing addresses
- [ ]  Remove invalid transactions & not show if txs are confirmed or not in the button detail view.

**Comment by Klakurka** [comment]
We could make a separate task for this but for BCH, we can have the 'confirmed' column like we have it in #350 but for XEC we'll want to use 'Finalized' instead. We might not be able to do finalized until we switch to Chronik though.

**Comment by Klakurka** [comment]
We're still showing a 'Confirmed' column for XEC but this should be changed to 'Finalized'.

**Comment by Klakurka** [comment]
The rest will be done as part of #240 and #241.
