### ISSUE TITLE
Switch XEC from BCHD to Chronik

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#411]
We can build against https://chronik.fabien.cash and then run our own instance eventually.

Docs: https://chronik.be.cash/docs/

**Comment by vorg-code** [comment]
Let's implement this migration in parts, the first PR will create the Chronik service, install dependencies and implement the getBalance method for a given address replacing the use of grpc by this new one across the project.

**Comment by Klakurka** [comment]
Some useful links:

- Example getAllTxHistory function: https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/web/alias-server/chronik.js#L120
- Example getAllTxHistory function: https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/web/cashtab/src/utils/chronik.js#L104
- Example parseChronikTx function: https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/web/cashtab/src/utils/chronik.js#L839
- Example outputScriptToAddress function: https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/web/cashtab/src/utils/cashMethods.js#L1248
- Example Chronik output: https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/web/alias-server/test/mocks/aliasMocks.js#L3

**Comment by Klakurka** [comment]
Still more to do on this one.
