### ISSUE TITLE
When selecting the suggested email for login, provided by the browser, the inputted text ends up being white

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#450]
Reproduced in Brave on Windows 11. It's likely caused by the OS dark mode but I'm not 100% sure.

![image](https://user-images.githubusercontent.com/4713204/228051535-104ee1e3-23aa-461c-9d95-2b174919ee9a.png)

**Comment by Klakurka** [comment]
This is an issue on both the light and dark modes of the site.

**Comment by johnkuney** [comment]
I can't seem to replicate this issue...and it may be a tricky one to track down as I think thats coming from the browser or something. I cant even seem to see what is applying the color when I inspect it. All of the CSS in the dev panel has the color rules on it crossed out. Not sure where its coming from. 

I was able to target the input text color through the supertokens config, but the autofill color overrides it...and supertokens doesnt have a setting for autofill color afaict 

Is this happening with anyone else @chedieck @vorg-code ?

**Comment by Klakurka** [comment]
One thought I had is that it might be coming from the Windows dark mode as I have that set on both of my work PCs but it's just a guess.

**Comment by johnkuney** [comment]
Yeah very well could be. Could maybe try disabling your dark mode if you want to test?

**Comment by johnkuney** [comment]
This should be good now with the custom login components, but let me know if still seeing

**Comment by Klakurka** [comment]
It's working totally fine now with the new pages.
