### ISSUE TITLE
Edit paybutton address should be more user friendly

### ISSUE THREAD

**Issue by chedieck** [PayButton/paybutton-server#466]
Suppose a user wants to add a BCH address to the following button:

![image](https://user-images.githubusercontent.com/21281174/230227501-8ee039d6-a124-45b8-80de-02c6b6b9d233.png)

the placeholder shows the currently present ecash address. So he would have to somehow type that all again, break a line, and add the bitcoincash address, which would be very annoying

**Comment by Klakurka** [comment]
Perhaps we can just put the address(es) in there as actual values rather than as a placeholder. I get that having it as a placeholder means that we can easily tell if it was actually changed or not when processing the submit but probably not a big deal.

**Comment by Klakurka** [comment]
Ya I think just putting the actual values in there is best. We can probably keep the placeholder in there just for their reference if they delete the value in there while editing.
