### ISSUE TITLE
Show past address transactions without refreshing

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#512]
Right now only new transactions show up without refreshing the page.

**Comment by Klakurka** [comment]
I'm actually not sure what this one is about... any ideas before I just close it?

I'm not sure what a "past transaction" refers to exactly.

**Comment by chedieck** [comment]
I don't know either, I think this already works well: both when syncing an address (fetching old txs) and when a new tx arrives from subscription we do send a websocket message to all clients so they don't have to refresh the page.

Closing it.
