### ISSUE TITLE
Big addresses smart handling

### ISSUE THREAD

**Issue by chedieck** [PayButton/paybutton-server#513]
1. **Big addresses syncing is non blocking** — When a big address (one with many txs) is added, its sync does not make so that addresses added afterwards have to wait for its sync to finish so they themselves start syncing.
2. **Mid-sync tx arrival is well handled** — if a big address is in the middle of the sync and a tx arrives, it's gonna be synced from the subscription job. Nonetheless, when the sync is almost over, this tx will appear again and we will try to sync it again. Therefore, it's necessary to make sure this will lead in an error and this attempt to save in the DB a tx that is already there is simply ignored.

**Comment by Klakurka** [comment]
We can push this to the v2 milestone if we can pre-sync the address before allowing public access and it's all working as expected for people.

**Comment by chedieck** [comment]
Cool, then it's as simple as adding the desired addresses to be pre-synced in a seeds file that is only seeded when ENV = production
