### ISSUE TITLE
Added button no longer visible but seems to still exist

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#545]
1. Added a button w/ an address that has lots of transactions in it (`ecash:qz3yu2m8dzwrw5uc85a5pz78dyxnrvdhf542l5ja56`).
2. No transactions showed up after waiting 20-30 seconds
3. Eventually it goes missing on the buttons page
4. Trying to re-add the button results in an error saying that it already exists
5. System jobs seem to be working hard in the background (in theory to sync the address) but the button is totally missing from the UI

**Comment by chedieck** [comment]
I just tried reproducing this and noticed the automatic sync of addresses was broken.
Opening a new PR that will fix it, should probably fix this too
