### ISSUE TITLE
Show "No transactions yet" on the buttons page if it's determined that there are no txs on a button when it goes to sync it

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#555]
I'm referring to the automatic process that replaces "Syncing address..." with the list of txs but if there are none, then it doesn't change until you manually refresh.

![image](https://github.com/PayButton/paybutton-server/assets/4713204/a5cf36b4-aa3a-4467-bdca-8b9f384bead4)

**Comment by chedieck** [comment]
This should already be working like so, if not it's a bug
