### ISSUE TITLE
Dark theme has black font on wallet selector on paybutton creation.

### ISSUE THREAD

**Issue by chedieck** [PayButton/paybutton-server#562]
Not possible to read the wallet name.

Dark theme:
![image](https://github.com/PayButton/paybutton-server/assets/21281174/17cec79f-5e28-4058-b85e-0246884b7d42)

Light theme:
![image](https://github.com/PayButton/paybutton-server/assets/21281174/b6bd707f-4278-45db-9507-d08a5042e952)

**Comment by Klakurka** [comment]
Likely related to #450.

**Comment by johnkuney** [comment]
This should be good now
