### ISSUE TITLE
"Create a button" module/page

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#6]

**Comment by Klakurka** [comment]
Probably appropriate to open from a button on the 'buttons' tab/page, and possibly on the landing page if they don't have any buttons added yet. John can decide.

**Comment by Klakurka** [comment]
Maybe we could have this be part of the "Create Button" UI somehow. It makes sense that people would want to save the look & function of their custom buttons beyond just which addresses are involved.

**Comment by Klakurka** [comment]
Also probably smart to do a mockup or two first before getting too far into it as it's a pretty big task.

**Comment by johnkuney** [comment]
Sorry, getting back up to speed here. So the idea here is to separate out the create button actions into its own page correct? As opposed to the modal its currently in? 

And you also want this accessible by people not signed in? Or just a link to it from the dashboard or landing page? And if they're signed in they can get to it? 

And Im not sure I follow the comment about saving the look and function of the button? The buttons dont have a "look" here right thats on the client side that you make a button right?

**Comment by Klakurka** [comment]
Not quite.

This is about making the actual button (HTML) that can be copied onto websites.

It's a GUI builder for buttons, kind of like what we have in Storybook.

For now, let's just have this be on the new landing page.

So it won't even require logging in, although if we had it available after logging in too then we could auto-fill more stuff.

**Comment by Klakurka** [comment]
https://PayButton.org has all of the options w/ their defaults.

**Comment by johnkuney** [comment]
Ah okay cool makes sense. Something else coming to mind for down the road, maybe we could add the button style/function definitions to the buttons in the dashboard? ie save the settings in the database, and users can see it visualized there and then come back and copy the html code again/tweak as they need?
