### ISSUE TITLE
Have login status change the landing page nav menu

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#601]
If you're logged in, navigating to the landing page now redirects you back to the dashboard. We should allow people to visit the dashboard if they want to even if they're logged in. Bonus points would be to show 'Dashboard' and 'Sign Out' instead of 'Sign Up' and 'Sign In' in the nav but we can v2 this if it's too much trouble.

**Comment by Klakurka** [comment]
We could also have the logo in the upper left take you to the landing page once this is in.

**Comment by chedieck** [comment]
1. Create link to Landing Page on the Sidebar,
2. Removes the Sidebar from the landing page,
3. Change "Sign In" and "Sign Up" for "'Dashboard" and " "Sign out" in the Landing Page, if logged in.
