### ISSUE TITLE
Add payment triggers / reactions (Webhooks) section

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#613]
Allow attaching a set of "payment triggers" to a button, managed through the /button/xxx page.

When a payment is received on an address within the button, do what they've set it to do.

Options:
- Send an email (eventually we can expand this once #543 is done) to send emails to different email addresses within their organization. For now we'll limit it to just their own.
- Send a POST request to a URL, with a custom JSON object that they can set (maybe in a provided textarea) with placeholders for the various values.

Data:
- Button name
- Payment address
- Currency
- Amount
- Datetime
- Payload / BIP 70 data (eg. tx id or other context; think Coin Dance supporters section)

Could have:
 - Display warning on the page when the user tries to add a payment trigger to a button that already has one attached to it that's defined in another button that shares one or more addresses (as we allow addresses to be associated with multiple buttons). If they choose to ignore the warning, they may find that they have multiple triggers firing for a single payment.
 - Send a text message (same idea as email).

**Comment by Klakurka** [comment]
For the UI, at the top of the section we'd have it say: "When a payment is received..." then we'd have maybe a checkbox toggle on each option to activate them.

**Comment by chedieck** [comment]
- send txId as data too,
- only allow one trigger per address for now

**Comment by Klakurka** [comment]
Let's also add a message signature that they can optionally check.

This will also require us to give everyone a private code / key which we can display on the same page used to generate the post requests (can put it below the form).

**Comment by Klakurka** [comment]
BIP 70 payload, email + text notifications will be done later.

**Comment by Klakurka** [comment]
Super cool.
