### ISSUE TITLE
Remove options from copyable code that are set to the default (button generator)

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#628]
Ideally, the button generator would be able to adapt automatically if at some point in the future the defaults changed (rather than hard coding them).

**Comment by johnkuney** [comment]
You mean like remove the prop from the copyable code if the value is the default?
Do you want to show the default values at all, or should all of the options be blank to start, and then only if a value is provided add it to the code? Could maybe also do the defaults as placeholders instead (but then would still be hardcoded in the site)

**Comment by Klakurka** [comment]
People can see all of the options they have available to them in the actual form and in /docs so let's hide the props+values from the displayed code unless it deviates from the default.

**Comment by Klakurka** [comment]
I missed this during the last review but there's still more to do.

**Comment by Klakurka** [comment]
Right now, the "hover-text", "currency", and "theme" appear in the code snippet out of the gate.

Remove the automatically-filled form value for "Hover Text". That will remove that from the snippet.

Have 'Currency' just behave like 'Animation' does where selecting XEC/BCH just removes it from the snippet.

For theme, we might need to re-test this once paybutton v2.0.0 has been published but the button should use the XEC blue and BCH green by default. If it doesn't then we can fix that later. But upshot is if they don't mess with the theme form controls then it shouldn't appear in the snippet.

'class' and 'to' are all that should be in there by default (assuming the client is working correctly).
