### ISSUE TITLE
Add button to allow viewing / copying all payments for a particular button, or set of buttons

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#803]
Add a small button to the /payments page which will either display a simple page of every payment where the text can be copied, or to a .CSV with the same data.

Columns (in order from left to right):
 - Date (YYYY-MM-DD)
 - Amount (in XEC); 2 decimal places
 - Value (in their preferred currency); 2 decimal places
 - Rate (value / amount); 14 decimal places
 - Transaction ID
 - Button Name

**Comment by Klakurka** [comment]
Maybe we can put the button on the end (right side) of the 'Transactions' title section on /button/xxx ?

![image](https://github.com/PayButton/paybutton-server/assets/4713204/9e517c98-d0d0-4bd2-95bd-01e6224d45c8)

**Comment by chedieck** [comment]
I think MVP here would be an "Export" button that exports it to CSV, you agree?

**Comment by lissavxo** [comment]
> Maybe we can put the button on the end (right side) of the 'Transactions' title section on /button/xxx ?
> 
> ![image](https://private-user-images.githubusercontent.com/4713204/329027087-9e517c98-d0d0-4bd2-95bd-01e6224d45c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMDI3NTcsIm5iZiI6MTcxNTIwMjQ1NywicGF0aCI6Ii80NzEzMjA0LzMyOTAyNzA4Ny05ZTUxN2M5OC1kMGQwLTRiZDItOTViZC0wMWU2MjI0ZDQ1YzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMjEwNzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDlmNGRhMTY2YWY4MDgwMjRmNjY2NjY5OWI5YzBhZWE1MDRhMmE1MzNjYzllOGI2OGQ2NWU4MDExMjMzZGM2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bkLlMIYnURKksc6SEe-10sdgk5Wr0V7EVPWFeJ9KkTA)

I think placing the button in the Transactions section inside the button details page is a good thing. If we add it in the /payments page it will download a lot of data because the page contains payments from all buttons of that user, I believe, so a lot of transactions to display in a single file.

**Comment by chedieck** [comment]
> Maybe we can put the button on the end (right side) of the 'Transactions' title section on /button/xxx ?

Here it would be per-address basis, since we show the transactions separated for each address a button has. Fine with me.

And, about the columns, considering that "Button Name" would then be redundant since it would always be the same, in this case would be best to have it (together with the address) in the file name. Maybe something like My_Button_name-ecash:myaddress.csv

As for how to implement, probably the best path is to create a table e.g. ExportJob with columns such as filePath, status, userId, type , and then create the ExportJob row upon request at first with status ONGOING and then when status is DONE update the view via websocket so the download of the file starts automatically.

Also probably a good idea to use generators when creating the file to avoid e.g. having 80000 transactions in memory while parsing all of them and writing to a file, best to have e.g. 500 at a time and achieve the same objective.

**Comment by Klakurka** [comment]
> I think MVP here would be an "Export" button that exports it to CSV, you agree?

We can try this for now and see how it works for us. We would be copy+pasting the data into a google spreadsheet and I'm not 100% sure how well it can handle pasting the contents of a CSV.

**Comment by Klakurka** [comment]
> > Maybe we can put the button on the end (right side) of the 'Transactions' title section on /button/xxx ?
> 
> Here it would be per-address basis, since we show the transactions separated for each address a button has. Fine with me.
> 
> And, about the columns, considering that "Button Name" would then be redundant since it would always be the same, in this case would be best to have it (together with the address) in the file name. Maybe something like My_Button_name-ecash:myaddress.csv
> 
> As for how to implement, probably the best path is to create a table e.g. `ExportJob` with columns such as `filePath`, `status`, `userId`, `type` , and then create the `ExportJob` row upon request at first with status ONGOING and then when status is DONE update the view via websocket so the download of the file starts automatically.
> 
> Also probably a good idea to use generators when creating the file to avoid e.g. having 80000 transactions in memory while parsing all of them and writing to a file, best to have e.g. 500 at a time and achieve the same objective.

The MVP needs to be per button, not per address. We can add export links for individual addresses too but it's not needed for our purposes and nobody else is asking for this (yet).
