### ISSUE TITLE
Navigating around can cause logged-in site nav to appear before actually being logged in

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton-server#860]
![image](https://github.com/user-attachments/assets/e985246d-5d96-4e17-b09c-179f495d613f)

To reproduce:

1. Navigate to https://paybutton.org/ (not logged in).
2. Click 'Sign In'.
3. Click 'Sign Up Now'.
4. Navigate back a page in the browser (so it goes back to 'Sign In').
5. You'll see the nav. Clicking any of the nav buttons will show you the 'Something went wrong.' error page.

**Comment by johnkuney** [comment]
This is happening on the live site for you?
I tried at paybutton.org but couldnt reproduce, but it does happen if I'm running locally

**Comment by johnkuney** [comment]
but not everytime lol

**Comment by Klakurka** [comment]
Yes I can reproduce it easily on the live site.

**Comment by Klakurka** [comment]
![image](https://github.com/user-attachments/assets/a615de00-579c-41e2-ada2-6d4136eaa723)

This is the live site (paybutton.org).

**Comment by johnkuney** [comment]
okay, yeah its odd I cant get it to do it at all now, but will check it out
