### ISSUE TITLE
Move from Sequelize to Prisma

### ISSUE THREAD

**Issue by chedieck** [PayButton/paybutton-server#87]
[Sequelize](sequelize.org/), mainly because it lacks a decent documentation and TypeScript compatibility, has already proved to be a huge source of bugs, and has already demanded a lot of work time dedicated to trying to find workarounds around things that should have been simple, some examples:
- TypeScript complains accessing any of the model objects, since it cannot infer this from typing. This means that we either cannot check for typing in tests, or we have to pollute a whole lot of our code with workarounds such as `// @ts-ignore`
- Updating the database is probably easier done with raw queries than with manually creating migration files, since these are not auto-generated from the model files, are not a single source of truth (SSOT), and the documentation for it... let's say that the only way to find how to properly use `Sequelize.queryInterface` methods are either lurking on obscure StackExchange threads or by hacking Sequelize source code itself. Many times these threads will provide raw queries solutions, unsurprisingly.

[Prisma](https://www.prisma.io/), unlike Sequelize, is well documented, built for typescript, supports auto-generated migrations and works through a SSOT scheme. It's also almost as popular as Sequelize, but Sequelize is still the most used ORM.

**Comment by Gattaca1** [comment]
Makes sense to have an ORM that plays better with TS. I'm in favour of this switch while the project is still young.

**Comment by chedieck** [comment]
I've separated this task into smaller ones, each of which I shall address in a different PR.

- [ ] Add & configure Prisma
- [ ] Remove `types/index.ts` and use Prisma generated types in its places
- [ ] Change `cross-env` for `dotenv`
- [ ] Change all sequelize queries for prisma queries;
- [ ] Change the database instantiation to use prisma instead of sequelize
- [ ] Change the prisma scheme so that table names / field names adhere with prisma conventions
- [ ] Remove sequelize from the project
